### ISSUE TITLE
ISSUE [w/ Fix] : Bug with Masking causes Major Toggle Issue

### ISSUE THREAD

**Issue by bradennapier** [nikgraf/belle#253] opened 2016-01-22 01:33 UTC
There is a bug with the toggle that when certain elements become rendered on the screen, the masking becomes messed up. 

![image](https://cloud.githubusercontent.com/assets/15365418/12500135/299a69c0-c065-11e5-9d92-47184b7a3ed8.png)

This style is required to resolve the issue:

```
   -webkit-mask-image:  url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA5JREFUeNpiYGBgAAgwAAAEAAGbA+oJAAAAAElFTkSuQmCC);
```

When this is added via inspector, it resolves the problem:

![image](https://cloud.githubusercontent.com/assets/15365418/12500139/3a86c0d0-c065-11e5-9d5d-32fabaf5ba53.png)

**Comment by nikgraf** [comment] 2016-01-22 16:58
interesting @bradennapier - do you have simple code example so I can reproduce it?

**Comment by rchanou** [comment] 2016-07-22 19:05
I also got this for certain toggles, though I haven't been able to isolate why. It seems to happen specifically in Chrome; Firefox and Edge show fine. The fix also works when applied via JS:

```
const toggleFixStyle = {
  WebkitMaskImage: 'url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA5JREFUeNpiYGBgAAgwAAAEAAGbA+oJAAAAAElFTkSuQmCC)'
};
...
<div>
  <Toggle /> {/* masking messed up */}
  <Toggle style={toggleFixStyle} /> {/* masking fixed */}
</div>
```

**Comment by rchanou** [comment] 2016-07-22 19:31
All right, it has to do with adjacent elements that have `-webkit-backface-visibility: hidden`. Here's a simple test case:

```
<div>
  <Toggle />
  <div style={{ WebkitBackfaceVisibility: 'hidden' }} />
</div>
```

The toggle should have bugged masking. Removing `-webkit-backface-visibility: hidden` via the inspector fixes it.

**Comment by rchanou** [comment] 2016-07-22 19:32
Probably just a Chrome bug we'll have to deal with.

**Comment by nikgraf** [comment] 2017-04-10 19:32
@rchanou are you still using it? does the bug still exist?

**Comment by rchanou** [comment] 2017-04-12 18:14
I don't know, I removed the offending `-webkit-backface-visibility: hidden` a while ago. Unless @bradennapier wants to chime in, I would say go ahead and close this because it appears to be a Chrome issue (which may be fixed by now), it's a rare case, and there's a documented workaround.

**Closed** 2017-10-10 20:56 UTC
